# Generated by Django 4.1.1 on 2022-10-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="spot", name="photo_User",),
        migrations.AlterField(
            model_name="spot",
            name="photo",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
